### ISSUE TITLE
The -e option should show Label foreign key edges?

### ISSUE THREAD

**Issue by csanyipal** [inukshuk/sqleton#4]
Hi,

I'm on a Gentoo Linux system.
I just installed Sqleton and it works fine.

I run it like this:
`sqleton -t "Az Oraim.db AdatTelep" -L twopi -e true -o diagramm_Oraim.pdf Oraim.db`
But there is not showing Labels of foreign key edges. Why?
One more question. Why is not showing the cardinality of keys?

Best, Paul

**Comment by inukshuk** [comment]
Oh, looks like the name of the `-e` option is spelled the wrong way internally. I'll fix that right away, thanks for reporting!

What do you mean exactly by cardinality of keys?

**Comment by csanyipal** [comment]
I mean this: one to one, one to many.

**Comment by inukshuk** [comment]
OK, I've pushed a new release fixing the `-e` options, thanks again for reporting!

This library is for visualizing actual db schemata which exist in the wild; it's not trying to reverse engineer an ER diagram from the schema, because I that would be hard to do. For example, how would you differentiate between a 1:1 and 1:n relationship based on the schema? What if there are no unique constraints defined?
